services:
  backend1: &backend-service
    image: rinhadebackend2025
    container_name: backend1
    hostname: backend1
    build:
      context: .
      dockerfile: RinhaDeBackend2025/Dockerfile
    expose:
      - "8080"
    ports:
      - "3001:8080"
    environment:
      - ASPNETCORE_URLS=http://*:8080
      - REDIS_CONNECTION_STRING=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "150MB"

  backend2:
    <<: *backend-service
    container_name: backend2
    ports:
      - "3002:8080"
    hostname: backend2

  nginx:
    image: nginx:1.25-alpine
    container_name: load-balance
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "15MB"
          
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "275MB"
          
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true